/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSessionRouteImport } from './routes/_authenticated/session'
import { Route as AuthenticatedSessionIndexRouteImport } from './routes/_authenticated/session/index'
import { Route as AuthenticatedSessionCreateRouteImport } from './routes/_authenticated/session/create'
import { Route as AuthenticatedSessionIdRouteImport } from './routes/_authenticated/session/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionRoute = AuthenticatedSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionIndexRoute =
  AuthenticatedSessionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionRoute,
  } as any)
const AuthenticatedSessionCreateRoute =
  AuthenticatedSessionCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSessionRoute,
  } as any)
const AuthenticatedSessionIdRoute = AuthenticatedSessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/session': typeof AuthenticatedSessionRouteWithChildren
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/session/create': typeof AuthenticatedSessionCreateRoute
  '/session/': typeof AuthenticatedSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/session/create': typeof AuthenticatedSessionCreateRoute
  '/session': typeof AuthenticatedSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/session': typeof AuthenticatedSessionRouteWithChildren
  '/_authenticated/session/$id': typeof AuthenticatedSessionIdRoute
  '/_authenticated/session/create': typeof AuthenticatedSessionCreateRoute
  '/_authenticated/session/': typeof AuthenticatedSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/session'
    | '/session/$id'
    | '/session/create'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/session/$id'
    | '/session/create'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/session'
    | '/_authenticated/session/$id'
    | '/_authenticated/session/create'
    | '/_authenticated/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/session': {
      id: '/_authenticated/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthenticatedSessionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/session/': {
      id: '/_authenticated/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof AuthenticatedSessionIndexRouteImport
      parentRoute: typeof AuthenticatedSessionRoute
    }
    '/_authenticated/session/create': {
      id: '/_authenticated/session/create'
      path: '/create'
      fullPath: '/session/create'
      preLoaderRoute: typeof AuthenticatedSessionCreateRouteImport
      parentRoute: typeof AuthenticatedSessionRoute
    }
    '/_authenticated/session/$id': {
      id: '/_authenticated/session/$id'
      path: '/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AuthenticatedSessionIdRouteImport
      parentRoute: typeof AuthenticatedSessionRoute
    }
  }
}

interface AuthenticatedSessionRouteChildren {
  AuthenticatedSessionIdRoute: typeof AuthenticatedSessionIdRoute
  AuthenticatedSessionCreateRoute: typeof AuthenticatedSessionCreateRoute
  AuthenticatedSessionIndexRoute: typeof AuthenticatedSessionIndexRoute
}

const AuthenticatedSessionRouteChildren: AuthenticatedSessionRouteChildren = {
  AuthenticatedSessionIdRoute: AuthenticatedSessionIdRoute,
  AuthenticatedSessionCreateRoute: AuthenticatedSessionCreateRoute,
  AuthenticatedSessionIndexRoute: AuthenticatedSessionIndexRoute,
}

const AuthenticatedSessionRouteWithChildren =
  AuthenticatedSessionRoute._addFileChildren(AuthenticatedSessionRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSessionRoute: typeof AuthenticatedSessionRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSessionRoute: AuthenticatedSessionRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
